# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a559644d68e07c95288b38b7ebc8e6d4d8945cd57ec0d40b2ab4511d537ced6a10f095434d749005e6e6f046ce85000779403aa8d693d00c4974c953a0b14adf

test:
  secret_key_base: 431ab30de85f049c3b0e42ddfa508df20d9a7f0b93d0bfd4cdd8bb9fbda5f782791225f04ef011b051122abfd6f977e3f7c7175d63dad27d20c86517ef9c5c83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
